########################################
# COMMON CONFIGURATION
########################################

# JTE

gg.jte.developmentMode=false
gg.jte.usePrecompiledTemplates=true

########################################
# JPA COMMON CONFIGURATION
########################################

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


########################################
# FILE UPLOAD CONFIGURATION
########################################

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


########################################
# DATE FORMAT
########################################

spring.jackson.date-format=MM-dd-yyyy